
// generated by C:\designvue\VUE2\src\build.xml
package tufts.vue;
/** generated by /Users/helenoliver/tuftsvue/trunk/VUE2/src/build.xml February 13 2013 2309 */
public final class Version {
/** February 13 2013 at 2309 by helenoliver on Mac OS X 10.6.8 x86_64 JVM 1.6.0_39-b04-442-10M4008 */
public static final String
        Date = "February 13 2013",
        Time = "2309",
        User = "helenoliver",
        Platform = "Mac OS X 10.6.8 x86_64",
        JVM = "1.6.0_39-b04-442-10M4008(bits=64)",
        AllInfo = "February 13 2013 at 2309 by helenoliver on " + Platform + " JVM " + JVM,
        WhatString = "@(#)VUE: built " + AllInfo;
}
