
// generated by C:\designvue\testbranch\VUE2\src\build.xml
package tufts.vue;
/** generated by C:\designvue\testbranch\VUE2\src\build.xml March 16 2013 1533 */
public final class Version {
/** March 16 2013 at 1533 by Rob Bracewell on Windows 7 6.1 x86 JVM 1.6.0_41-b02 */
public static final String
        Date = "March 16 2013",
        Time = "1533",
        User = "Rob Bracewell",
        Platform = "Windows 7 6.1 x86",
        JVM = "1.6.0_41-b02(bits=32)",
        AllInfo = "March 16 2013 at 1533 by Rob Bracewell on " + Platform + " JVM " + JVM,
        WhatString = "@(#)VUE: built " + AllInfo;
}
